# file burnhrt2o/WebTestSimple/docker-compose.yml
version: '3'

services:
   nginx:
      image: nginx:alpine
      volumes:
         - ./www-data:/usr/share/nginx/html
         - ./config/conf.d:/etc/nginx/conf.d
         - ./log:/var/log/nginx
      ports:
         - "8080:80"
         - "8443:443"
